services:
  - type: web
    name: mls-mcp-server
    runtime: docker
    # Fixed path to match the nested structure in GitHub
    dockerfilePath: ./mls-mcp-server/Dockerfile
    env: docker
    autoDeploy: true
    port: 8080
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
