services:
  - type: web
    name: mls-mcp-server
    runtime: docker
    dockerfilePath: ./Dockerfile
    env: docker
    autoDeploy: true
    port: 8080
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
