services:
  - type: web
    name: mls-mcp-server
    runtime: docker
    rootDir: ./mls-mcp-server # Set the build root to the subdirectory
    dockerfilePath: ./Dockerfile # Path is relative to rootDir
    env: docker
    autoDeploy: true
    port: 8080
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
